name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python: "3.12"
      - name: Run linters
        # Temporarily disabled so I get CI up and running and I can fix the new
        # lint errors separately.
        run: |
            nox -ts --python=3.12 --tags lint || true
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy3.9", "pypy3.10"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python: ${{ matrix.python }}
      - name: Run typechecking
        run: |
            nox -ts --python=${{ matrix.python }} -e mypy
      - name: Run tests
        run: |
            nox -ts --python=${{ matrix.python }} -e test
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python }}
          path: |
            coverage.test-${{ matrix.python }}
            junit.test-${{ matrix.python }}.xml
  coverage:
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python: "3.12"
      - uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          path: .
      - name: Move files
        run: mv test-results*/coverage.* .
      - name: Generate coverage report
        run: |
            nox -ts --python=3.12 -e coverage
      - name: Upload coverage results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            htmlcov
            coverage.xml
  docs:
    runs-on: ubuntu-latest
    needs:
      - lint
      - check
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python: "3.12"
      - name: Build docs
        run: |
          nox -ts -e docs
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            docs/build
  package:
    runs-on: ubuntu-latest
    needs:
      - lint
      - check
      - docs
      - coverage
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python: "3.12"
      - uses: actions/download-artifact@v4
        with:
          pattern: docs
          path: docs/build
      - name: Build package
        run: |
          nox -ts -e build
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
