name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.7, 3.8, 3.9, "3.10", "3.11", "pypy3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Cache .tox directory
        uses: actions/cache@v3
        with:
            path: .tox
            key: ${{ runner.os }}-tox-${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip tox~=3.20
      - name: Run tox
        env:
            COV_REPORT: term
        run: |
            python="${{ matrix.python }}" tox -e py${python#py}
  package:
    runs-on: ubuntu-latest
    needs:
      - check
    strategy:
      matrix:
        python: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Cache .tox directory
        uses: actions/cache@v3
        with:
            path: .tox
            key: ${{ runner.os }}-tox-${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip tox~=3.20
      - name: Build docs
        run: |
          tox -e docs
      - name: Build package
        run: |
          tox -e build
